/**
 * 30가지 임상·상담 진단 모듈 — docs/internal-materials/ta-clinical-modules/
 * WizCoCo 검사: 이고 50 + 오케이 40 + 타당도 6 = 96문항
 */

export type ClinicalModuleScaleId = 'CP' | 'NP' | 'A' | 'FC' | 'AC' | 'I+' | 'I-' | 'U+' | 'U-';

export type ClinicalModuleComputeKind =
  | 'weighted'
  | 'ratio_cp_np'
  | 'ratio_fc_ac'
  | 'energy_sum'
  | 'life_position'
  | 'burnout_risk'
  | 'strong_hurry';

export type ClinicalModulePolarity = 'strength' | 'risk' | 'neutral';

export type ClinicalModuleDef = {
  id: number;
  part: 1 | 2 | 3 | 4 | 5 | 6;
  titleKo: string;
  titleEn: string;
  accuracyPct: number;
  feature: string;
  pros: string;
  cons: string;
  itemNote: string;
  weights: Partial<Record<ClinicalModuleScaleId, number>>;
  invert?: ClinicalModuleScaleId[];
  compute: ClinicalModuleComputeKind;
  polarity: ClinicalModulePolarity;
};

export const CLINICAL_MODULE_ITEM_BANK = {
  egogramPerScale: 10,
  egogramTotal: 50,
  okPerScale: 10,
  okTotal: 40,
  validity: 6,
  total: 96,
} as const;

export const CLINICAL_MODULE_QUICK_TIP = {
  screening: '활력(3) → 자아 프로파일(1)+인생태도(2) → 드라이버(25~27)',
  resistance: '예-하지만(22)·이면교류(15)가 높으면 A 계약(Contract) 중심 개입을 우선 검토',
} as const;

export const CLINICAL_MODULES_30: ClinicalModuleDef[] = [
  {
    id: 1,
    part: 1,
    titleKo: '핵심 자아상태 프로파일',
    titleEn: 'Core Egogram Profile',
    accuracyPct: 85,
    feature: 'CP·NP·A·FC·AC 고저를 그래프로 성격 뼈대 진단',
    pros: '직관적 시각화로 내담자가 구조를 즉각 이해',
    cons: 'V형·N형 등 형태에만 매몰되면 맥락을 간과할 위험',
    itemNote: '50문항 (이고그램 전체)',
    weights: { CP: 0.2, NP: 0.2, A: 0.2, FC: 0.2, AC: 0.2 },
    compute: 'weighted',
    polarity: 'neutral',
  },
  {
    id: 2,
    part: 1,
    titleKo: '실존적 인생태도 매트릭스',
    titleEn: 'OK-Matrix Position',
    accuracyPct: 83,
    feature: 'I±·U± 조합으로 근본적 세계관·대인 신뢰 수준 진단',
    pros: '핵심 인지 도식과 신뢰 수준을 한 번에 파악',
    cons: 'I+U+ 위장 응답(사회적 바람직성)에 취약',
    itemNote: '40문항 (오케이그램) + 인생태도 좌표',
    weights: { 'I+': 0.25, 'I-': 0.25, 'U+': 0.25, 'U-': 0.25 },
    compute: 'life_position',
    polarity: 'neutral',
  },
  {
    id: 3,
    part: 1,
    titleKo: '심리적 활력·에너지 총량',
    titleEn: 'Psychic Energy Level',
    accuracyPct: 78,
    feature: '5자아 총점으로 동원 가능한 심리 에너지 측정',
    pros: '만성 우울·무기력·치료 초기 고갈 스크리닝',
    cons: '내면 갈등으로 낭비되는 에너지와 구별 어려움',
    itemNote: '50문항 (이고그램 합산)',
    weights: { FC: 0.3, A: 0.25, NP: 0.2, CP: 0.15, AC: 0.1 },
    compute: 'energy_sum',
    polarity: 'strength',
  },
  {
    id: 4,
    part: 1,
    titleKo: '부모 자아 균형 (CP–NP)',
    titleEn: 'CP-NP Critical/Nurturing Ratio',
    accuracyPct: 81,
    feature: '규율·통제(CP) vs 돌봄·수용(NP) 비율',
    pros: '양육·부부 상담에서 훈육 갈등 원인 규명',
    cons: '직장 vs 가정 등 상황에 따라 발현이 달라짐',
    itemNote: '20문항 (CP 10 + NP 10)',
    weights: { CP: 0.5, NP: 0.5 },
    compute: 'ratio_cp_np',
    polarity: 'neutral',
  },
  {
    id: 5,
    part: 1,
    titleKo: '어린이 자아 해방 (FC–AC)',
    titleEn: 'FC-AC Spontaneity/Adaptation Ratio',
    accuracyPct: 80,
    feature: '감정 분출(FC) vs 타인 눈치·순응(AC) 비율',
    pros: '내면아이 상처·억압된 분노·자발성 결여 포착',
    cons: 'FC 과다 시 A와 교차 검증 필요(충동 vs 자발)',
    itemNote: '20문항 (FC 10 + AC 10)',
    weights: { FC: 0.5, AC: 0.5 },
    compute: 'ratio_fc_ac',
    polarity: 'neutral',
  },
  {
    id: 6,
    part: 1,
    titleKo: '이성적 현실검증력 (A)',
    titleEn: 'Adult Reality Testing Capacity',
    accuracyPct: 84,
    feature: 'A 중심으로 사실·논리 처리 역량',
    pros: '계약 기반·인지행동적 개입 가능 기초 확인',
    cons: '과도하면 지성화(Intellectualization) 방어 가능',
    itemNote: '30문항 가중 (A·CP·FC)',
    weights: { A: 0.7, CP: 0.15, FC: 0.15 },
    compute: 'weighted',
    polarity: 'strength',
  },
  {
    id: 7,
    part: 2,
    titleKo: '자존감·자기수용 (I+)',
    titleEn: 'Self-Acceptance / I+ Level',
    accuracyPct: 84,
    feature: '실패·비판 속 자기 가치 유지(내적 탄력)',
    pros: '열등감·자기비하·수치심 목표 설정에 필수',
    cons: '나르시시즘적 방어 시 왜곡 가능',
    itemNote: '20문항 (I+·I-)',
    weights: { 'I+': 0.6, 'I-': 0.4 },
    invert: ['I-'],
    compute: 'weighted',
    polarity: 'strength',
  },
  {
    id: 8,
    part: 2,
    titleKo: '대인 신뢰·방어 (U+)',
    titleEn: 'Interpersonal Trust / U+ Level',
    accuracyPct: 82,
    feature: '타인을 협력적·안전 vs 위협으로 보는 경향',
    pros: '치료적 동맹(Rapport) 형성 난이도 예측',
    cons: '트라우마 경계를 병리로 오판 위험',
    itemNote: '20문항 (U+·U-)',
    weights: { 'U+': 0.6, 'U-': 0.4 },
    invert: ['U-'],
    compute: 'weighted',
    polarity: 'strength',
  },
  {
    id: 9,
    part: 2,
    titleKo: '스트로크 결핍·갈망',
    titleEn: 'Stroke Hunger Index',
    accuracyPct: 77,
    feature: '인정·칭찬에 대한 강박적 갈망',
    pros: '의존성·타인 중심 동기 분석',
    cons: '갈망 자체를 수치스러워 축소 보고 가능',
    itemNote: '30문항 가중 (AC·I-·U+)',
    weights: { AC: 0.4, 'I-': 0.35, 'U+': 0.25 },
    compute: 'weighted',
    polarity: 'risk',
  },
  {
    id: 10,
    part: 2,
    titleKo: '부정적 스트로크 수집',
    titleEn: 'Negative Stroke Seeking',
    accuracyPct: 73,
    feature: '비난·무시·동정을 유도해 관심을 얻는 패턴',
    pros: '부당한 대우 반복 관계의 자각 촉진',
    cons: '저항·자책감 유발 — 조심스러운 직면 필요',
    itemNote: '30문항 가중',
    weights: { AC: 0.35, 'I-': 0.35, 'U-': 0.3 },
    compute: 'weighted',
    polarity: 'risk',
  },
  {
    id: 11,
    part: 2,
    titleKo: '라켓 감정 치환',
    titleEn: 'Racket Feeling Vulnerability',
    accuracyPct: 71,
    feature: '진짜 감정 대신 익숙한 가짜 감정으로 대체',
    pros: '정화 단계에서 표면 정서 너머 감정 타겟',
    cons: '설문만으로 무의식 치환 포착 한계',
    itemNote: '30문항 가중',
    weights: { AC: 0.45, CP: 0.3, 'I-': 0.25 },
    compute: 'weighted',
    polarity: 'risk',
  },
  {
    id: 12,
    part: 2,
    titleKo: '죄책감·수치심 민감도',
    titleEn: 'Guilt & Shame Proneness',
    accuracyPct: 81,
    feature: '타인 실망·부정 사건을 전적으로 자기 탓',
    pros: '신경증적 우울·자학 성향 감별',
    cons: '직면 시 고통 가중 — 지지적 환경 선행',
    itemNote: '30문항 가중',
    weights: { AC: 0.45, CP: 0.3, 'I-': 0.25 },
    compute: 'weighted',
    polarity: 'risk',
  },
  {
    id: 13,
    part: 3,
    titleKo: '의사소통 상보성',
    titleEn: 'Complementary Interaction Index',
    accuracyPct: 78,
    feature: '상대 자아에 맞춰 대화를 안정적으로 유지',
    pros: '사회적 적응·라포 잠재력 객관화',
    cons: '본질 갈등을 덮는 피상적 조화 가능',
    itemNote: '30문항 가중',
    weights: { A: 0.35, NP: 0.35, 'U+': 0.3 },
    compute: 'weighted',
    polarity: 'strength',
  },
  {
    id: 14,
    part: 3,
    titleKo: '교차적 교류·단절 위험',
    titleEn: 'Crossed Transaction Risk',
    accuracyPct: 75,
    feature: '기대와 엇갈린 자아로 반응해 대화 단절',
    pros: '말다툼·오해·단절 촉발 요인 피드백',
    cons: '상대 공격성을 배제하고 내담자만 귀인 위험',
    itemNote: '30문항 가중',
    weights: { CP: 0.4, FC: 0.3, 'U-': 0.3 },
    compute: 'weighted',
    polarity: 'risk',
  },
  {
    id: 15,
    part: 3,
    titleKo: '이면 교류(이중 화법)',
    titleEn: 'Ulterior Transaction Tendency',
    accuracyPct: 72,
    feature: '표면 A 아래 은밀한 심리 메시지',
    pros: '수동공격·돌려 말하기·조작적 소통 통찰',
    cons: '「그냥 돌려 말한 것」 합리화 쉬움',
    itemNote: '30문항 가중',
    weights: { AC: 0.35, 'U-': 0.35, A: 0.3 },
    invert: ['A'],
    compute: 'weighted',
    polarity: 'risk',
  },
  {
    id: 16,
    part: 3,
    titleKo: '경계·거절 역량',
    titleEn: 'Boundary Setting & Refusal Capacity',
    accuracyPct: 82,
    feature: '무리한 부탁에 건강하게 No',
    pros: '착한 아이·관계 과부하 — 자율성 회복 훈련',
    cons: '거절 훈련 초기 2차 갈등 가능',
    itemNote: '30문항 가중',
    weights: { A: 0.4, 'I+': 0.3, AC: 0.3 },
    invert: ['AC'],
    compute: 'weighted',
    polarity: 'strength',
  },
  {
    id: 17,
    part: 3,
    titleKo: '공감적 경청·수용',
    titleEn: 'Empathic Listening Capacity',
    accuracyPct: 83,
    feature: '판단 없이 정서적 지지·온기 전달',
    pros: '부부·가족 치료 연결감 회복 자원',
    cons: '과도 시 대리 외상·정서 흡수 위험',
    itemNote: '30문항 가중',
    weights: { NP: 0.5, 'U+': 0.35, A: 0.15 },
    compute: 'weighted',
    polarity: 'strength',
  },
  {
    id: 18,
    part: 3,
    titleKo: '권위적 통제·지배',
    titleEn: 'Authoritarian Control Index',
    accuracyPct: 81,
    feature: 'CP·U- 중심 교정·훈계·지배',
    pros: '갑질·가부장적 권위 소통 조기 경고',
    cons: '도덕적 정당화로 상담 저항',
    itemNote: '30문항 가중',
    weights: { CP: 0.6, 'U-': 0.3, NP: 0.1 },
    invert: ['NP'],
    compute: 'weighted',
    polarity: 'risk',
  },
  {
    id: 19,
    part: 4,
    titleKo: '드라마 삼각: 박해자',
    titleEn: 'Persecutor Role Risk',
    accuracyPct: 76,
    feature: '갈등 시 상대 비난·심판으로 우위',
    pros: '관계 파탄 공격성을 상담실에서 객관화',
    cons: '낙인·조기 탈락 위험',
    itemNote: '30문항 가중',
    weights: { CP: 0.5, 'U-': 0.35, 'I+': 0.15 },
    compute: 'weighted',
    polarity: 'risk',
  },
  {
    id: 20,
    part: 4,
    titleKo: '드라마 삼각: 구원자 번아웃',
    titleEn: 'Rescuer Burnout Risk',
    accuracyPct: 78,
    feature: '요청 없는 도움·통제감 유지',
    pros: '헌신형 번아웃·공동의존 보상 심리',
    cons: '선의 부정당함 상처·배신감',
    itemNote: '30문항 가중',
    weights: { NP: 0.5, 'I+': 0.25, 'U-': 0.25 },
    compute: 'weighted',
    polarity: 'risk',
  },
  {
    id: 21,
    part: 4,
    titleKo: '드라마 삼각: 희생자 수동성',
    titleEn: 'Victim Passivity Risk',
    accuracyPct: 77,
    feature: '무력감 호소·타인이 대신 해결 기대',
    pros: '상담 정체·과의존 전이 예방',
    cons: '실제 피해 vs 심리 게임 감별 필요',
    itemNote: '30문항 가중',
    weights: { AC: 0.5, 'I-': 0.3, 'U+': 0.2 },
    compute: 'weighted',
    polarity: 'risk',
  },
  {
    id: 22,
    part: 4,
    titleKo: '「예, 하지만」 저항',
    titleEn: 'Yes-But Resistance',
    accuracyPct: 74,
    feature: '조언 구한 뒤 모든 대안 거부',
    pros: '조언 남발 방지·수동 저항 다루기',
    cons: '상담사 역전이·좌절 쉬움',
    itemNote: '30문항 가중',
    weights: { AC: 0.4, 'U-': 0.3, A: 0.3 },
    invert: ['A'],
    compute: 'weighted',
    polarity: 'risk',
  },
  {
    id: 23,
    part: 4,
    titleKo: '책임 전가 (See What You Made Me Do)',
    titleEn: 'Blame / External Locus',
    accuracyPct: 75,
    feature: '실패를 타인·환경 탓으로 돌림',
    pros: '피해의식·외적 통제위 탐색',
    cons: '직면 시 상담사를 적으로 돌릴 위험',
    itemNote: '30문항 가중',
    weights: { 'U-': 0.4, CP: 0.35, AC: 0.25 },
    compute: 'weighted',
    polarity: 'risk',
  },
  {
    id: 24,
    part: 4,
    titleKo: '친밀성 회피·시간 구조화',
    titleEn: 'Intimacy Avoidance Index',
    accuracyPct: 76,
    feature: 'Ritual·Pastimes·Withdrawal 편중',
    pros: '회피형 애착·깊은 관계 공포',
    cons: '내향·휴식 욕구와 혼동 주의',
    itemNote: '40문항 가중',
    weights: { 'U-': 0.35, 'I-': 0.25, A: 0.2, FC: 0.2 },
    invert: ['FC'],
    compute: 'weighted',
    polarity: 'risk',
  },
  {
    id: 25,
    part: 5,
    titleKo: 'Be Perfect 드라이버',
    titleEn: 'Be Perfect Driver',
    accuracyPct: 84,
    feature: '완벽해야만 가치 있다는 조건적 신념',
    pros: '강박·검토증·지연 행동 근본',
    cons: '고성과로 문제 부인 쉬움',
    itemNote: '30문항 가중',
    weights: { CP: 0.45, A: 0.3, 'I-': 0.25 },
    compute: 'weighted',
    polarity: 'risk',
  },
  {
    id: 26,
    part: 5,
    titleKo: 'Please Others 드라이버',
    titleEn: 'Please Others Driver',
    accuracyPct: 85,
    feature: '타인 기분 맞추기 위해 자기 욕구 지움',
    pros: '관계 피로·분노 억압·우울 직결 설명',
    cons: '패턴 해체 시 유기 불안',
    itemNote: '30문항 가중',
    weights: { AC: 0.45, NP: 0.25, 'I-': 0.3 },
    compute: 'weighted',
    polarity: 'risk',
  },
  {
    id: 27,
    part: 5,
    titleKo: 'Be Strong / Hurry Up',
    titleEn: 'Be Strong & Hurry Up',
    accuracyPct: 82,
    feature: '약점 숨김·조급·긴장 지속',
    pros: '공황·긴장성 신체화 배경',
    cons: '취약성 드러내기에 강한 저항',
    itemNote: '30문항 (CP·A·FC)',
    weights: { CP: 0.35, A: 0.35, FC: 0.3 },
    compute: 'strong_hurry',
    polarity: 'risk',
  },
  {
    id: 28,
    part: 5,
    titleKo: '번아웃 취약',
    titleEn: 'Burnout Vulnerability',
    accuracyPct: 82,
    feature: 'CP·AC 높고 FC·NP 낮은 소진 패턴',
    pros: '적극 치료 전 휴식 처방 설득',
    cons: '일시 과로 vs 구조적 소진 구별',
    itemNote: '40문항 (CP·AC·FC·NP)',
    weights: { CP: 0.3, AC: 0.3, FC: 0.2, NP: 0.2 },
    compute: 'burnout_risk',
    polarity: 'risk',
  },
  {
    id: 29,
    part: 6,
    titleKo: '각본 재결정 잠재력',
    titleEn: 'Script Re-decision Index',
    accuracyPct: 76,
    feature: '금지령 극복·삶 재선택 준비도',
    pros: '후반 Script Cure 예후 지표',
    cons: 'A 미발달 시 충동적 반항으로 변질',
    itemNote: '30문항 가중',
    weights: { A: 0.4, 'I+': 0.3, FC: 0.3 },
    compute: 'weighted',
    polarity: 'strength',
  },
  {
    id: 30,
    part: 6,
    titleKo: '종합 자율성·성숙도',
    titleEn: 'Overall Autonomy Index',
    accuracyPct: 79,
    feature: '각각성·자발성·친밀성 종합',
    pros: '종결 시 치료 효과·전후 비교',
    cons: '총괄 지표 — 세부 행동은 하위 척도 병행',
    itemNote: '40문항 가중',
    weights: { A: 0.25, FC: 0.25, 'I+': 0.25, 'U+': 0.25 },
    compute: 'weighted',
    polarity: 'strength',
  },
];

export const CLINICAL_MODULE_PART_LABELS: Record<number, string> = {
  1: '핵심 자아구조·에너지',
  2: '자존감·내면 방어',
  3: '대인·의사소통',
  4: '게임·드라마 삼각',
  5: '드라이버·스트레스',
  6: '치료·변화 잠재력',
};
